In [1]:
import pandas as pd
import numpy as np

### обработка данных

In [2]:
data = pd.read_csv('D:\data_for_ml\data.csv')
data

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\mikha\AppData\Local\Temp\ipykernel_14356\4159996275.py:1: SyntaxWarning: invalid escape sequence '\d'
  data = pd.read_csv('D:\data_for_ml\data.csv')


9.48153782478  394.853786783
0         6.878546     238.295702
1         9.436524     393.053669
2         3.572694      55.666155
3         1.079596      13.537515
4         9.487563     395.101230
..             ...            ...
994       8.714093     366.701156
995       3.783151      60.254649
996       9.104563     380.503300
997       1.717459      32.758233
998       7.288236     277.359814

[999 rows x 2 columns]

$f(x) = ((a+\varepsilon_a) \cdot sin(x) + (b+ \varepsilon_b)ln(x))^2 + (c + \varepsilon_c)x^2$

In [3]:
data_np = np.array(data)

In [4]:
a = 1
b = 1 
c = 1


In [5]:
from math import sin
from math import log

In [6]:
A = [[]]
for i in range(data.shape[0]):
    x = data_np[i][0]
    A.append([sin(x)**2, 2*sin(x) * log(x), log(x)**2, x**2])


In [7]:
A

[[],
 [0.31450541345886535,
  2.162931866175294,
  3.7187549542199045,
  47.314401670091556],
 [0.00013797366860372024,
  -0.05273083980292096,
  5.0381741213017595,
  89.04799369978859],
 [0.1746163428742145,
  -1.0641673550192463,
  1.6213433130718249,
  12.764139020933133],
 [0.7775133838494724,
  0.1350631951925183,
  0.005865515332127063,
  1.1655269529518704],
 [0.003936780126643546,
  -0.2823446589452677,
  5.062418008526592,
  90.01385106379543],
 [0.9392055735727876,
  0.5405590442686458,
  0.07777958536518048,
  1.7467900254446964],
 [0.3889977508663472,
  1.126970958926085,
  0.8162409290504813,
  6.091662663173707],
 [0.5945195203475707,
  1.258127861659634,
  0.6656155357854563,
  5.112585714252422],
 [0.8888346870983742,
  1.2208624945360762,
  0.4192301594998072,
  3.650848860822351],
 [0.4932807462010274,
  1.2078772308249404,
  0.7394204091592249,
  5.583362317382748],
 [0.6507450971738812,
  -0.10236057203472307,
  0.004025265327690998,
  0.880830596077529],
 [0.99482

In [8]:
A.pop(0)

[]

In [9]:
A = np.array(A)
A

array([[ 3.14505413e-01,  2.16293187e+00,  3.71875495e+00,
         4.73144017e+01],
       [ 1.37973669e-04, -5.27308398e-02,  5.03817412e+00,
         8.90479937e+01],
       [ 1.74616343e-01, -1.06416736e+00,  1.62134331e+00,
         1.27641390e+01],
       ...,
       [ 9.90805180e-02,  1.39051523e+00,  4.87869018e+00,
         8.28930678e+01],
       [ 9.78643840e-01,  1.07007904e+00,  2.92514267e-01,
         2.94966547e+00],
       [ 7.12655363e-01,  3.35356100e+00,  3.94523494e+00,
         5.31183849e+01]])

In [10]:
b = [[]]
for i in range(data.shape[0]):
    b.append(data_np[i][1])

In [11]:
b.pop(0)

[]

In [12]:
b = np.array(b)
b

array([238.29570215, 393.05366889,  55.66615523,  13.5375153 ,
       395.10122956,  21.45473871,  43.85542514,  41.98763998,
        36.89432117,  42.9808774 ,   9.10536432,  26.90027596,
        60.36961615,  45.40127339,   3.21455855,  25.61956338,
       407.70876392,   7.015962  , 368.37186823,  34.23981322,
       116.32554491,  39.61597452,  44.61096236,  54.41383993,
        33.44585353,  97.76289825, 321.33273227, 302.06545095,
       405.19055801,  66.47801336,   4.15765564, 158.494363  ,
       333.07929659,  20.9382632 ,  50.30325667, 381.92698982,
       377.33489068, 327.92421753, 266.99921794, 201.71053962,
        90.5959493 ,  48.2276204 ,  64.76227313, 134.9564399 ,
       173.2346996 , 374.97438601, 214.49324047,  88.230055  ,
        37.84520369,  66.90738141,   2.85487923,  22.99653884,
       388.5055559 ,  73.83031799,  71.37495787, 302.33479687,
       363.37053864,  30.69278473,  44.74499037, 108.00360129,
       379.99251883, 154.53636724,  36.21075828,  46.29

### решим матрицами

In [13]:
A_sort = A[:4]
A_sort
b_sort = b[:4]

In [14]:
A_inv = np.linalg.inv(A_sort)

In [15]:
X = A_inv @ b_sort

In [16]:
X

array([9.87383743, 8.5284565 , 7.35471428, 4.00287163])

In [17]:
from math import sqrt

In [18]:
print(sqrt(X[0]))
print(sqrt(X[2]))
print(X[3])

3.1422662887562818
2.711957646769566
4.002871634525766


решил просто матрицами 